services:
  frontend:
    build:
      context: ./frontend/my-rag-frontend
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    depends_on:
      - postgres
      - minio

  postgres:
    image: pgvector/pgvector:pg18

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data_v18:/var/lib/postgresql

  minio:
    image: minio/minio:latest

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

volumes:
  postgres_data_v18:
  minio_data:
